# Generated by Django 3.0.3 on 2021-02-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='number',
            field=models.IntegerField(default=2),
        ),
    ]
