# Generated by Django 3.0.3 on 2021-02-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment_generator', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
