# Generated by Django 3.0.3 on 2020-11-05 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docker_image', models.CharField(max_length=200)),
                ('default_docker_filepath', models.CharField(max_length=200)),
                ('deployment_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kubernetes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_name', models.CharField(max_length=100)),
                ('config_data_path', models.CharField(max_length=200)),
                ('yaml_deployments', models.CharField(max_length=200)),
                ('def_helmchart_path', models.CharField(max_length=200)),
                ('helm_deployments', models.CharField(max_length=200)),
                ('docker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devops.Docker')),
            ],
        ),
        migrations.CreateModel(
            name='Github',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('cloned_directory', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Endpoints',
            fields=[
                ('ports', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('kubernetes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devops.Kubernetes')),
            ],
        ),
        migrations.AddField(
            model_name='docker',
            name='github',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devops.Github'),
        ),
    ]
