# Generated by Django 3.0.3 on 2020-12-14 12:00

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docker_image', models.CharField(max_length=200)),
                ('default_docker_filepath', models.CharField(max_length=200)),
                ('deployment_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Github',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('cloned_directory', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('docker_image_name', models.CharField(max_length=200)),
                ('kubernetes_deployment_name', models.CharField(max_length=200)),
                ('directory', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path_urls', to='devops.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('extra_fields', jsonfield.fields.JSONField()),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devops.Path')),
            ],
        ),
        migrations.CreateModel(
            name='Kubernetes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_name', models.CharField(max_length=100)),
                ('config_data_path', models.CharField(max_length=200)),
                ('yaml_deployments', models.CharField(max_length=200)),
                ('def_helmchart_path', models.CharField(max_length=200)),
                ('helm_deployments', models.CharField(max_length=200)),
                ('docker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kubernetes_profile', to='devops.Docker')),
            ],
        ),
        migrations.CreateModel(
            name='Endpoints',
            fields=[
                ('ports', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('kubernetes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devops.Kubernetes')),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('port', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('kubernetes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devops.Kubernetes')),
                ('path', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endpoint_path', to='devops.Path')),
            ],
        ),
        migrations.AddField(
            model_name='docker',
            name='github',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docker_profile', to='devops.Github'),
        ),
    ]
