# Generated by Django 3.0.3 on 2020-11-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoints',
            name='kubernetes',
        ),
        migrations.RemoveField(
            model_name='github',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kubernetes',
            name='docker',
        ),
        migrations.DeleteModel(
            name='Docker',
        ),
        migrations.DeleteModel(
            name='Endpoints',
        ),
        migrations.DeleteModel(
            name='Github',
        ),
        migrations.DeleteModel(
            name='Kubernetes',
        ),
    ]
