# Generated by Django 3.0.3 on 2021-02-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='kubernetes',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='path',
        ),
        migrations.RemoveField(
            model_name='endpoints',
            name='kubernetes',
        ),
        migrations.RemoveField(
            model_name='kubernetes',
            name='docker',
        ),
        migrations.RemoveField(
            model_name='project',
            name='docker_image_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='kubernetes_deployment_name',
        ),
        migrations.AddField(
            model_name='project',
            name='username',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Docker',
        ),
        migrations.DeleteModel(
            name='Endpoint',
        ),
        migrations.DeleteModel(
            name='Endpoints',
        ),
        migrations.DeleteModel(
            name='Github',
        ),
        migrations.DeleteModel(
            name='Kubernetes',
        ),
    ]
