# Generated by Django 3.0.3 on 2021-02-11 08:07

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0002_auto_20210208_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='initial_config',
            field=jsonfield.fields.JSONField(default={'config': 'yes'}),
            preserve_default=False,
        ),
    ]
