# Generated by Django 3.0.3 on 2020-11-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0003_auto_20201114_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='github',
            name='user',
        ),
    ]
