# Generated by Django 3.0.3 on 2020-11-14 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0004_remove_github_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docker',
            name='github',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_obj', to='devops.Github'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='path',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endpoint_path', to='devops.Path'),
        ),
    ]
