# Generated by Django 3.0.3 on 2020-11-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0005_auto_20201114_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docker',
            name='github',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docker_profile', to='devops.Github'),
        ),
    ]
