# Generated by Django 3.0.3 on 2020-11-14 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0006_auto_20201114_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubernetes',
            name='docker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kubernetes_profile', to='devops.Docker'),
        ),
    ]
