# Generated by Django 3.0.3 on 2020-11-14 17:40

import datetime
import devops.models
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0007_auto_20201114_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='description',
        ),
        migrations.RemoveField(
            model_name='method',
            name='operation_id',
        ),
        migrations.RemoveField(
            model_name='method',
            name='summary',
        ),
        migrations.AddField(
            model_name='method',
            name='extra_fields',
            field=devops.models.JSONField(default=datetime.datetime(2020, 11, 14, 17, 40, 8, 232094, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='method',
            name='path',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devops.Path'),
            preserve_default=False,
        ),
    ]
